#!/usr/bin/env bash

backend="transformers"
model="deepseek-ai/deepseek-coder-6.7b-instruct"
template="You are an AI programming assistant, utilizing the Deepseek Coder model, developed by Deepseek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer.
### Instruction:
Explain this code step by step:
{}
### Response:"

# todo: could take list of files as input instead and include file name

python3 lm.py \
    --backend "$backend" \
    --model "$model" \
    --template "$template" \
    "$@"